version: '3'

services:
  #########################################################################
  # substrate
  #########################################################################
  substrate:
    build:
      context: .
      dockerfile: ./docker/substrate/Dockerfile
    stdin_open: true
    tty: true
    command: bash -c "touch d.txt && tail -f d.txt"

  #########################################################################
  # rust
  #########################################################################
  rust:
    build:
      context: .
      dockerfile: ./docker/rust/Dockerfile
    environment:
      - USER=$USER
    volumes:
      - ./app/:/app
    stdin_open: true
    tty: true
#    command: bash -c "rustc main.rs && ./main"
    command: bash -c "touch /d.txt && tail -f /d.txt"